import './style.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.bundle.min.js'
import './components/NavComponent.js'
import './components/HomeComponent.js'
import './components/AboutComponent.js'
import './components/SkillsComponent.js'
import './components/FooterComponent.js'